ChorusOne/chorus-one-sdk

book/build-your-staking-dapp/avalanche/overview.md, book/build-your-staking-dapp/cosmos/overview.md, book/build-your-staking-dapp/ethereum/overview.md, book/build-your-staking-dapp/near/overview.md, book/build-your-staking-dapp/polkadot-substrate/overview.md, book/build-your-staking-dapp/solana/overview.md, book/build-your-staking-dapp/ton/overview.md, book/docs/classes/ethereum_src.EthereumStaker.md, book/docs/interfaces/ethereum_src.Transaction.md, book/ethereum-tutorial/3-staking.md, book/ethereum-tutorial/4-unstaking.md, book/ethereum-tutorial/5-minting-os-eth.md, book/ethereum-tutorial/6-burning-os-eth.md, packages/ethereum/src/lib/connector.ts, packages/ethereum/src/lib/methods/buildBurnTx.ts, packages/ethereum/src/lib/methods/buildMintTx.ts, packages/ethereum/src/lib/methods/buildStakeTx.ts, packages/ethereum/src/lib/methods/buildUnstakeTx.ts, packages/ethereum/src/lib/methods/buildWithdrawTx.ts, packages/ethereum/src/lib/methods/getTxHistory.ts, packages/ethereum/src/lib/types/transaction.ts, packages/ethereum/src/staker.ts
Ethereum:
- Fix all assets withdrawal
- Fix getTxHistory - now it returns Txs for specific delegators, not just all Txs
- Define & explain fee calculation
- Validate amounts and explain their format in the docs, since it is different from the main libs
- Add viem & ethers examples
- Minor code & docs improvements
All networks:
- Better lib compatibility notice in docs
=> Ethereum updates

packages/staking-cli/package.json, packages/substrate/package.json, packages/substrate/src/staker.ts
The problem occurs when a single validator is being passed in the Array and `...params` resolves it to single string which polkadot api doesn't expect
Tested with:
```
npm run staking-cli -- substrate tx delegate 0.1
npm run staking-cli -- substrate tx nominate 0.1
npm run staking-cli -- substrate tx bond-extra 0.1
npm run staking-cli -- substrate tx unbond 0.1
npm run staking-cli -- substrate tx withdraw
```
=> substrate: fix nomination to a single validator

packages/staking-cli/README.avalanche.md, packages/staking-cli/README.cosmos.md, packages/staking-cli/README.ethereum.md, packages/staking-cli/README.near.md, packages/staking-cli/README.polkadot.md, packages/staking-cli/README.ton.md
Add the demo recordings to the README.md
=> add staking-cli demos to README

book/build-your-staking-dapp/ton/ton-pool/methods.md, book/docs/classes/ton_src.TonPoolStaker.md, packages/ton/src/TonPoolStaker.ts
Adding referrer for TON tx for tracking.
To parse those fields from transactions, you can use:
```typescript
const txStatus = await this.getTxStatus({
address: 'kQDeHoxmpJ6dzzl7KyHDQuOSkwvEnXMcs-8gMCJOSo-IpTrj',
txHash: '37fd26a86aafd6fb05953655a0ecbe7ba5f1955002f105127359555f5151e733'
})
const body = txStatus.receipt?.outMessages.get(0)?.body.beginParse()
const op = body.loadUint(32)
const queryId = body.loadUint(64)
const gas = body.loadCoins()
const referrer = body.loadStringTail()
console.log({
op,
queryId,
gas,
referrer
})
``` 
Output:
```js
{
op: 2077040623,
queryId: 4090730133165079,
gas: 100000n,
referrer: 'Hello TON!!!'
}
```
Tx:
https://testnet.tonviewer.com/transaction/37fd26a86aafd6fb05953655a0ecbe7ba5f1955002f105127359555f5151e733?section=trace
=> Add referrer field for TON staking tx

package-lock.json, packages/ton/package.json, packages/ton/src/TonBaseStaker.ts
1. Retry if RPC request hits rate limit
2. Track both external and internal txs via getTxStatus:
When we send messages via SDK, we get their message hash. Then this reaches the wallet contract and it creates TX with outgoing messages. TX has both incoming and outgoing messages and has its own hash. 
getTxStatus was tracking only **TX** hash, and broadcast was returning **message** hash. So with getTxStatus it was not possible to track broadcasted messages. This PR fixes it
=> Improve TON Staker

package-lock.json, packages/staking-cli/src/cmd/ton.ts, packages/ton/package.json, packages/ton/src/TonBaseStaker.ts, packages/ton/src/TonClient.ts, packages/ton/src/TonPoolStaker.ts, packages/ton/src/types.d.ts, packages/ton/test/pool-staker.spec.ts
Ton Pool has two pools. We want to naively balance the pools so that ideally two pools are always in set.
This PR implements the naive balancing, by taking into account:
1. `minStake` - the amount of stake required for a pool to be in the set (taken from the lowest validator stake in past election)
2. `maxStake` - the maximum amount of stake allowed per pool (taken from chain config)
3. `poolBalance` - the current amount of available stake on the pool contract
The logic (to which u can see unittests) is simple, at first it'll try to fill up at least one if both are below minimum stake, and if both are above min, it'll fill the one with lower stake. 
If both are above maximum it will throw error. @welldan97 - Is that okay? or shall we allow people to stake above max?
```
$ npm run …
```
=> balance stake for both ton pool contracts

packages/staking-cli/src/cmd/ton.ts, packages/ton/src/TonBaseStaker.ts, packages/ton/src/TonClient.ts, packages/ton/src/TonNominatorPoolStaker.ts, packages/ton/src/TonPoolStaker.ts, packages/ton/src/TonSingleNominatorPoolStaker.ts, packages/ton/src/types.d.ts, packages/ton/test/pool-staker.spec.ts
Those are the changes after `npm run cleanup` for ton package
=> run cleanup on ton package

package-lock.json, packages/staking-cli/src/cmd/ton.ts, packages/ton/package.json, packages/ton/src/TonBaseStaker.ts, packages/ton/src/types.d.ts
BIP39 seeds are used by ledger devices and hierarchical wallets. This change is backwards compatible since previously the hdpath had to be empty.
run staking operation on main branch:
```
$ npm run staking-cli -- ton tx delegate-pool 0.1 -c ./config.tonpool.testnet.json -s local -b
https://testnet.tonviewer.com/transaction/6e8898baff49de738b37c3f03f2fc783eefe31b2af2df59a441918449b6f8002
```
run staking operation on `ton_support_bip39_keys` branch:
```
$ npm run staking-cli -- ton tx delegate-pool 0.1 -c ./config.tonpool.testnet.json -s local -b
https://testnet.tonviewer.com/transaction/c54c1da73eafb64597abfe4649a48bde5ab191a50f778246d8ed293ae0353d41
```
Config:
```
{
"delegatorAddress": "0QBDG13T98PFkLCpnXzkSPlrDp39aUUhQXTqFaad5cJU4uaz",
"validatorAddress": …
```
=> support BIP39 seeds for TON

package-lock.json, packages/signer-ledger-ton/LICENSE, packages/signer-ledger-ton/README.md, packages/signer-ledger-ton/package.json, packages/signer-ledger-ton/src/index.ts, packages/signer-ledger-ton/src/signer.ts, packages/signer-ledger-ton/src/types.d.ts, packages/signer-ledger-ton/tsconfig.cjs.json, packages/signer-ledger-ton/tsconfig.json, packages/signer-ledger-ton/tsconfig.mjs.json, packages/staking-cli/package.json, packages/staking-cli/src/enums.ts, packages/staking-cli/src/signer.ts, packages/staking-cli/src/types.d.ts, packages/ton/src/TonBaseStaker.ts, packages/ton/src/tx.ts, packages/ton/src/types.d.ts
This PR adds support for signing TON transaction via ledger device. Unfortunately there is a limitation that a transaction with one message can be signed, but that's fine for most of the things we want to execute.
This transaction is signed via ledger app
```
$ npm run staking-cli -- ton tx delegate-pool 0.1 -c ./config.tonpool.testnet.json -s ledger -b
https://testnet.tonviewer.com/transaction/86ecfbcb1c009c8d0a40f7e48727df23d2ee8c207aa97a31a89dc25f4bf8f917
```
Config
```json
{
"delegatorAddress": "0QBDG13T98PFkLCpnXzkSPlrDp39aUUhQXTqFaad5cJU4uaz",
"validatorAddress": "kQAHBakDk_E7qLlNQZxJDsqj_ruyAFpqarw85tO-c03fK26F",
"validatorAddress2": "kQCltujow9Sq3ZVPPU6CYGfqwDxYwjlmFGZ1Wt0bAYebio4o",
"ledger": {
"bounceable": false,
"accounts": [
{
"hdPath": "m/44'/607'/1'/0'/0'/0'"
}
]
}, …
```
=> [stacked] add ledger ton support

packages/ton/src/TonBaseStaker.ts, packages/ton/src/types.d.ts
Add some extra info to why the transaction failed
closes: #22
=> add ton reason for tx status check

book/docs/classes/ton_src.TonPoolStaker.md, packages/ton/src/TonBaseStaker.ts, packages/ton/src/TonPoolStaker.ts, packages/ton/src/types.d.ts
This is to handle the exit code correctly, closes #18
=> Handle 501 ton exit code

packages/cosmos/package.json, packages/cosmos/src/client.ts, packages/signer-cactus-cosmos/src/signer.ts, packages/signer-cactus-cosmos/src/types.d.ts, packages/signer-keplr/src/signer.ts
1. deps update - cosmos nodes moved forward with new types that are not in older version. The upgrade fixes the broadcast return message parsing
2. cactus - the `signAmino` fix
3. keplr - the wallet attempts to update the txfees which breaks the signature (signs smth different), plus minor fix on the signature format
=> upgrade cosmos and relevant signers

packages/staking-cli/package.json, packages/staking-cli/src/cmd/ton.ts, packages/ton/package.json, packages/ton/src/TonPoolStaker.ts, packages/ton/src/types.d.ts, packages/ton/test/pool-staker.spec.ts
Currently user can stake only to one pool at the time. This PR adds logic in which the stake is 'balanced' among the contracts.
The logic is tested via unittests. It may look a bit complicated since it takes into account, pool balance and minimum stake per deposit. Depending on the pool status it balances out things as fair as I thought it can be done.
```
$ npm run staking-cli -- ton tx delegate-pool 0.5 -c config.tonpool.testnet.json -s local
Error: amount is less than the minimum required stake
$ npm run staking-cli -- ton tx delegate-pool 1.2 -c config.tonpool.testnet.json -s local
Staking to the following contracts:
* kQCltujow9Sq3ZVPPU6CYGfqwDxYwjlmFGZ1Wt0bAYebio4o with 1.2 TON (1200000000 nanoTON)
$ npm run staking-cli -- ton tx delegate-pool 2 -c config.tonpool.testnet.json -s …
```
=> ton pool: stake to both pools at once

packages/ethereum/test/lib/hardhat.json
Ethereum tests are failing due to the rpc we're using in testing
=> Update forking URL in hardhat config

packages/cosmos/package.json, packages/cosmos/src/configurator.ts
all testnets have `testnet` in the chain name, so it's a safe assumption to prefix the path. See:
https://github.com/cosmos/chain-registry/tree/master/testnets
=> cosmos: support testnets in configurator

package-lock.json, packages/ton/package.json, packages/ton/src/TonBaseStaker.ts
Issue: https://github.com/ChorusOne/chorus-one-sdk/issues/58
Bug added on: https://github.com/ChorusOne/chorus-one-sdk/commit/ad330dc3732d180fae06f05ca495992967915b77
The API expected the header `Content-Type: application/json` , but with the new config of the httpAdapter the header is set to `content-type: text/plain;charset=UTF-8`
Version 2.0.0 it's the last working version.
=> Fix TON header request

packages/cosmos/package.json, packages/cosmos/src/configurator.ts, packages/cosmos/src/staker.ts, packages/cosmos/src/tx.ts, packages/cosmos/src/types.d.ts
This change enables the auto-estimation of gas usage. It calls `tx.simulate` with signer public key etc and gets back the gas used.
=> Cosmos auto gas fee

packages/ton/src/TonPoolStaker.ts, packages/ton/src/utils.ts, packages/ton/test/pool-staker.spec.ts
Before: 
- SDK didn't allow withdraw from pools bellow minElectionStake
- SDK didn't take into account minUserStake per pool
This changes fixes the two issues above and introduce more test cases for TON and 5 fallback strategies for unstaking prioritizing pool liveness: 
- Best scenario keep both pools active
- userMaxUnstakeToKeepPoolActive1, userMaxUnstakeToKeepPoolActive2
- Keep pool 1 active
- userMaxUnstakeToKeepPoolActive1, userMaxUnstakeAbsolute2
- userMaxUnstakeToKeepPoolActive1, userMaxUnstakeToKeepAboveMin2
- Keep pool 2 active
- userMaxUnstakeToKeepPoolActive2, userMaxUnstakeToKeepAboveMin1
- userMaxUnstakeToKeepPoolActive2, userMaxUnstakeAbsolute1
- Deactivate both pools
- userMaxUnstakeToKeepAboveMin1, userMaxUnstakeToKeepAboveMin2
- userMaxUnstakeAbsolute1, …
=> Include minElectionStake and minUserStake validation on TON SDK

package-lock.json, packages/ethereum/package.json, packages/ethereum/src/lib/methods/getRewardsHistory.ts, packages/ethereum/test/getRewardsHistory.spec.ts
The cumulative rewards data was wrong; stakewise api does not return cumulative data anymore.
Current approach: we fetch all entries since vault creation - ~600 days for the first stakewise vault, 565 days for mev max vault. Then we calculate the cumulative total from daily rewards.
There is a caveat, api only allows to fetch up to 1000 days. Which means in 400 days, it would throw an error.
=> Ethereum fix rewards data

package-lock.json, packages/ton/package.json, packages/ton/src/TonPoolStaker.ts
Currently the TON RPC requests are made all in parallel leading to hit the RPC limit (even on RPC paid plans). 
This PR make them sequential to avoid this issue
=> Make TON requests sequential instead of parallel

packages/cosmos/src/staker.ts, packages/ethereum/src/constants.ts, packages/ethereum/src/lib/methods/buildMintTx.ts, packages/ethereum/src/lib/methods/buildStakeTx.ts, packages/ethereum/src/lib/utils/getDefaultTrackingAddress.ts, packages/solana/src/staker.ts, packages/solana/src/tx.ts, packages/ton/src/TonPoolStaker.ts, packages/utils/src/index.ts
Include default referrer on sdk tx for SOL, ETH, TON, Cosmos
Testing: 
- Solana: https://explorer.solana.com/tx/4uj161oMZCEafonmB2H5J233cBTA5935Mqxa8cJKpU3r6iwWjeEFcxih1R9YEfAJFtoZoKns24jWqcuUB2HnVmFz?cluster=devnet
- TON: https://testnet.tonviewer.com/transaction/3d7cbadef54e0dffb093e11c86fbbea21cc05c7658d87bc85e0c7f0bb35a299e
- Cosmos: https://explorer.mantrachain.io/MANTRA-Dukong/tx/DD2FCEDFD75F1FDBA37AB3564AC224168C7492F3CBD7DC347A57C259740F14D9
- Ethereum: https://hoodi.etherscan.io/tx/0x9c3c9fc0c14e5425d25094390b14bf38625a9137d0219139f1d68a44c01e38e0
=> Include default referrer on sdk tx
